title: "The Code Den"
description: "I *do not* know what I am doing™"
url: "https://atirut-w.github.io"
baseurl: ""
livereload: true
permalink: /posts/:year/:month/:day/:title/

# remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
